### ISSUE TITLE
Any interest in PR that works off a list of URLs?

### ISSUE THREAD

**Issue by mhkeller** [mabhub/puppeteer-screenshot-cli#9]
I put together a quick addition that lets you point the cli at a file containing a list of URLs. I have a couple things to work out still but wondering if you'd want this as a PR and have some thoughts on the implementation or if I should just carry on a separate lib. Fine for me either way / happy to contribute back.

https://github.com/mhkeller/puppeteer-screenshot-cli

**Comment by mabhub** [comment]
I really like the idea of giving the ability to take multiple screenshots at once *(to be honest it was planned in a way)*, but I'm kind of sceptic by the way you implemented it.

You added of dependency to `npm` (I suppose this is by mistake) and to `indian-ocean` which I know you are the author. I've no doubt about the quality of this package, but I don't think it should be part of a command line screenshot tool *(where a [`fs.readFile()`](https://nodejs.org/api/fs.html#fs_fs_readfile_path_options_callback) would do the job)*.

A better approach would be to be able to take URLs from `stdin`. *(And maybe could a command line port of `indian-ocean` be able to provide file list through `stdout`)*

Another important point is that we should avoid launching a new browser instance for each URL. It would be better launching only one instance of browser and parallelize screenshots.

Anyway, thank you very much in taking interest over this tool.

About the code you've already produced, you'll understand that it's not currently suitable for a PR, but if you try another approach like I suggest, we would be pleased to review your proposal.

I've created an issue dedicated to this feature request (#10) so we can close this one (this would not prevent you from commenting here if you need).

Once again, thank you.

**Comment by mhkeller** [comment]
Thanks for the thoughtful reply. Sounds good. And woops, meant to update my npm not save it, thanks for the catch!

Ya I could see doing `fs.readFile` and then splitting on line breaks if that's not too system-dependent. I was keeping the option open to store some other metadata which could be handed to the screenshot file name for easier reference, for example. But maybe not necessary.

Using one browser instance is a good idea but I would keep an option for running them in serial so you can be nice to the server you're running them against if you have a lot. 

I'm mostly settled on this small use case of mine so I'll look forward to what you end up doing re: #10!
